In [2]:
import pandas as pd
import numpy as np

In [3]:
from sklearn import preprocessing

In [4]:
X_train=np.array([[1.,-1.,2.],[2.,0.,0.],[0.,1.,-1.]])

In [5]:
X_scale=preprocessing.scale(X_train)

In [6]:
X_scale.mean(axis=0)

array([0., 0., 0.])

In [7]:
X_scale.std(axis=0)

array([1., 1., 1.])

In [10]:
wd=pd.read_csv('wine.csv')

In [11]:
wd

Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0       1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1       1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2       1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3       1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4       1    13.24        2.59  2.87  21.0  118     2.80        2.69   
5       1    14.20        1.76  2.45  15.2  112     3.27        3.39   
6       1    14.39        1.87  2.45  14.6   96     2.50        2.52   
7       1    14.06        2.15  2.61  17.6  121     2.60        2.51   
8       1    14.83        1.64  2.17  14.0   97     2.80        2.98   
9       1    13.86        1.35  2.27  16.0   98     2.98        3.15   
10      1    14.10        2.16  2.30  18.0  105     2.95        3.32   
11      1    14.12        1.48  2.32  16.8   95     2.20        2.43   
12      1    13.75        1.73  2.41  16.0   89     2.60        2.76   
13      1    14.75        1.73  2.39  11.4   91     3.10        3.69   
14      1    14.38        1.87  2.38  12.0  102     3.30        3.64   
15      1    13.63        1.81  2.70  17.2  112     2.85        2.91   
16      1    14.30        1.92  2.72  20.0  120     2.80        3.14   
17      1    13.83        1.57  2.62  20.0  115     2.95        3.40   
18      1    14.19        1.59  2.48  16.5  108     3.30        3.93   
19      1    13.64        3.10  2.56  15.2  116     2.70        3.03   
20      1    14.06        1.63  2.28  16.0  126     3.00        3.17   
21      1    12.93        3.80  2.65  18.6  102     2.41        2.41   
22      1    13.71        1.86  2.36  16.6  101     2.61        2.88   
23      1    12.85        1.60  2.52  17.8   95     2.48        2.37   
24      1    13.50        1.81  2.61  20.0   96     2.53        2.61   
25      1    13.05        2.05  3.22  25.0  124     2.63        2.68   
26      1    13.39        1.77  2.62  16.1   93     2.85        2.94   
27      1    13.30        1.72  2.14  17.0   94     2.40        2.19   
28      1    13.87        1.90  2.80  19.4  107     2.95        2.97   
29      1    14.02        1.68  2.21  16.0   96     2.65        2.33   
..    ...      ...         ...   ...   ...  ...      ...         ...   
148     3    13.32        3.24  2.38  21.5   92     1.93        0.76   
149     3    13.08        3.90  2.36  21.5  113     1.41        1.39   
150     3    13.50        3.12  2.62  24.0  123     1.40        1.57   
151     3    12.79        2.67  2.48  22.0  112     1.48        1.36   
152     3    13.11        1.90  2.75  25.5  116     2.20        1.28   
153     3    13.23        3.30  2.28  18.5   98     1.80        0.83   
154     3    12.58        1.29  2.10  20.0  103     1.48        0.58   
155     3    13.17        5.19  2.32  22.0   93     1.74        0.63   
156     3    13.84        4.12  2.38  19.5   89     1.80        0.83   
157     3    12.45        3.03  2.64  27.0   97     1.90        0.58   
158     3    14.34        1.68  2.70  25.0   98     2.80        1.31   
159     3    13.48        1.67  2.64  22.5   89     2.60        1.10   
160     3    12.36        3.83  2.38  21.0   88     2.30        0.92   
161     3    13.69        3.26  2.54  20.0  107     1.83        0.56   
162     3    12.85        3.27  2.58  22.0  106     1.65        0.60   
163     3    12.96        3.45  2.35  18.5  106     1.39        0.70   
164     3    13.78        2.76  2.30  22.0   90     1.35        0.68   
165     3    13.73        4.36  2.26  22.5   88     1.28        0.47   
166     3    13.45        3.70  2.60  23.0  111     1.70        0.92   
167     3    12.82        3.37  2.30  19.5   88     1.48        0.66   
168     3    13.58        2.58  2.69  24.5  105     1.55        0.84   
169     3    13.40        4.60  2.86  25.0  112     1.98        0.96   
170     3    12.20        3.03  2.32  19.0   96     1.25        0.49   
171     3    12.77        2.39  2.28  19.5   

In [12]:
wd.head()


Wine  Alcohol  Malic.acid   Ash   Acl   Mg  Phenols  Flavanoids  \
0     1    14.23        1.71  2.43  15.6  127     2.80        3.06   
1     1    13.20        1.78  2.14  11.2  100     2.65        2.76   
2     1    13.16        2.36  2.67  18.6  101     2.80        3.24   
3     1    14.37        1.95  2.50  16.8  113     3.85        3.49   
4     1    13.24        2.59  2.87  21.0  118     2.80        2.69   

   Nonflavanoid.phenols  Proanth  Color.int   Hue    OD  Proline  
0                  0.28     2.29       5.64  1.04  3.92     1065  
1                  0.26     1.28       4.38  1.05  3.40     1050  
2                  0.30     2.81       5.68  1.03  3.17     1185  
3                  0.24     2.18       7.80  0.86  3.45     1480  
4                  0.39     1.82       4.32  1.04  2.93      735

In [13]:
wd.keys()


Index(['Wine', 'Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols',
       'Flavanoids', 'Nonflavanoid.phenols', 'Proanth', 'Color.int', 'Hue',
       'OD', 'Proline'],
      dtype='object')

In [15]:
wd.shape

(178, 14)

In [16]:
wd.describe()

Wine     Alcohol  Malic.acid         Ash         Acl          Mg  \
count  178.000000  178.000000  178.000000  178.000000  178.000000  178.000000   
mean     1.938202   13.000618    2.336348    2.366517   19.494944   99.741573   
std      0.775035    0.811827    1.117146    0.274344    3.339564   14.282484   
min      1.000000   11.030000    0.740000    1.360000   10.600000   70.000000   
25%      1.000000   12.362500    1.602500    2.210000   17.200000   88.000000   
50%      2.000000   13.050000    1.865000    2.360000   19.500000   98.000000   
75%      3.000000   13.677500    3.082500    2.557500   21.500000  107.000000   
max      3.000000   14.830000    5.800000    3.230000   30.000000  162.000000   

          Phenols  Flavanoids  Nonflavanoid.phenols     Proanth   Color.int  \
count  178.000000  178.000000            178.000000  178.000000  178.000000   
mean     2.295112    2.029270              0.361854    1.590899    5.058090   
std      0.625851    0.998859              0.124453    0.572359    2.318286   
min      0.980000    0.340000              0.130000    0.410000    1.280000   
25%      1.742500    1.205000              0.270000    1.250000    3.220000   
50%      2.355000    2.135000              0.340000    1.555000    4.690000   
75%      2.800000    2.875000              0.437500    1.950000    6.200000   
max      3.880000    5.080000              0.660000    3.580000   13.000000   

              Hue          OD      Proline  
count  178.000000  178.000000   178.000000  
mean     0.957449    2.611685   746.893258  
std      0.228572    0.709990   314.907474  
min      0.480000    1.270000   278.000000  
25%      0.782500    1.937500   500.500000  
50%      0.965000    2.780000   673.500000  
75%      1.120000    3.170000   985.000000  
max      1.710000    4.000000  1680.000000

In [17]:
wd.describe().transpose()

count        mean         std     min       25%  \
Wine                  178.0    1.938202    0.775035    1.00    1.0000   
Alcohol               178.0   13.000618    0.811827   11.03   12.3625   
Malic.acid            178.0    2.336348    1.117146    0.74    1.6025   
Ash                   178.0    2.366517    0.274344    1.36    2.2100   
Acl                   178.0   19.494944    3.339564   10.60   17.2000   
Mg                    178.0   99.741573   14.282484   70.00   88.0000   
Phenols               178.0    2.295112    0.625851    0.98    1.7425   
Flavanoids            178.0    2.029270    0.998859    0.34    1.2050   
Nonflavanoid.phenols  178.0    0.361854    0.124453    0.13    0.2700   
Proanth               178.0    1.590899    0.572359    0.41    1.2500   
Color.int             178.0    5.058090    2.318286    1.28    3.2200   
Hue                   178.0    0.957449    0.228572    0.48    0.7825   
OD                    178.0    2.611685    0.709990    1.27    1.9375   
Proline               178.0  746.893258  314.907474  278.00  500.5000   

                          50%       75%      max  
Wine                    2.000    3.0000     3.00  
Alcohol                13.050   13.6775    14.83  
Malic.acid              1.865    3.0825     5.80  
Ash                     2.360    2.5575     3.23  
Acl                    19.500   21.5000    30.00  
Mg                     98.000  107.0000   162.00  
Phenols                 2.355    2.8000     3.88  
Flavanoids              2.135    2.8750     5.08  
Nonflavanoid.phenols    0.340    0.4375     0.66  
Proanth                 1.555    1.9500     3.58  
Color.int               4.690    6.2000    13.00  
Hue                     0.965    1.1200     1.71  
OD                      2.780    3.1700     4.00  
Proline               673.500  985.0000  1680.00

In [18]:
#SETTING OUR DATA AND lABELS

In [22]:
x=wd.drop("Wine",axis=1)

In [23]:
Y=wd["Wine"]

In [27]:
#splitting our data
from sklearn.model_selection import train_test_split

In [31]:
X_train,X_test,y_train,y_test=train_test_split(x,Y,test_size=.20)


In [32]:
#Data preprocessing

In [33]:
from sklearn.preprocessing import StandardScaler

In [34]:
ms=StandardScaler()

In [35]:
ms.fit(X_train)

C:\Users\hp\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)


StandardScaler(copy=True, with_mean=True, with_std=True)

In [36]:
X_train=ms.transform(X_train)

C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """Entry point for launching an IPython kernel.


In [37]:
type(X_train)

numpy.ndarray

In [38]:
#training the model

In [40]:
from sklearn.neural_network import MLPClassifier

In [43]:
mlp=MLPClassifier(hidden_layer_sizes=(13,13,13),max_iter=500)

In [44]:
#training with data

In [47]:
mlp.fit(X_train,y_train)

MLPClassifier(activation='relu', alpha=0.0001, batch_size='auto', beta_1=0.9,
       beta_2=0.999, early_stopping=False, epsilon=1e-08,
       hidden_layer_sizes=(13, 13, 13), learning_rate='constant',
       learning_rate_init=0.001, max_iter=500, momentum=0.9,
       n_iter_no_change=10, nesterovs_momentum=True, power_t=0.5,
       random_state=None, shuffle=True, solver='adam', tol=0.0001,
       validation_fraction=0.1, verbose=False, warm_start=False)

In [48]:
mm=mlp.fit(X_train,y_train)

In [49]:
#predicition and evaluation

In [50]:
nm=mm.predict(X_test)

In [57]:
nm

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int64)

In [58]:
from sklearn import metrics

In [59]:
metrics.accuracy_score(y_test,nm)

0.3055555555555556

In [60]:
from sklearn.metrics import classification_report,confusion_matrix


In [61]:
confusion_matrix(y_test,nm)

array([[11,  0,  0],
       [12,  0,  0],
       [13,  0,  0]], dtype=int64)

In [64]:
classification_report(y_test,nm)

'              precision    recall  f1-score   support\n\n           1       0.31      1.00      0.47        11\n           2       0.00      0.00      0.00        12\n           3       0.00      0.00      0.00        13\n\n   micro avg       0.31      0.31      0.31        36\n   macro avg       0.10      0.33      0.16        36\nweighted avg       0.09      0.31      0.14        36\n'